version: "3.3"


services:
  spring:
    environment:
    - MONGO_DB_HOSTNAME=mongo
    - MONGO_DB_USERNAME=harichandana
    - MONGO_DB_PASSWORD=password

  mongo:
   environment:
   - MONGO_INITDB_ROOT_USERNAME=harichandana
   - MONGO_INITDB_ROOT_PASSWORD=password
